### ISSUE TITLE
Commands - comments and questions

### ISSUE THREAD

**Issue by gobyrne** [kheaactua/diplomacy-engine#2]
Here are the current commands:

```
Convoy.php: '%empire% %cmd% %source%-%dest%'
Retreat.php:    '%empire% %cmd% %source%-%dest%'
Hold.php:   '%empire% %cmd% %source%'
Move.php:   '%empire% %cmd% %source%-%dest%'
Support.php:    '%empire% %cmd% %ally% %source%-%dest%'
Disband.php:    '%empire% %cmd% %source%'
```
- The convoy needs a "mid" to identify the actual territory that it is in.
- The %ally% in support is not needed since only 1 unit can be in that territory
- Is the %dest% in support optional or do you need to specify the same territory twice to support a hold? The later is actually probably simpler for me.

**Comment by gobyrne** [comment]
Also, can we get rid of all the "-" I don't think they actually add anything now that computers are handling commands... and I don't want to write an if statement to show or hide them...

**Comment by gobyrne** [comment]
Actually the Support command is similar to the convoy in that you need a third territory identified. Here what I recommend for all commands

``` text
Convoy.php:   '%empire% %cmd% %territory% %dest% %source%'
Retreat.php:    '%empire% %cmd% %territory% %dest%'
Hold.php:         '%empire% %cmd% %territory%'
Move.php:        '%empire% %cmd% %territory% %dest%'
Support.php:    '%empire% %cmd% %territory% %dest% %source%'
Disband.php:    '%empire% %cmd% %territory%'
Create.php:      '%empire% %cmd% %territory%'
```

**Comment by kheaactua** [comment]
About support, I suppose you could use the territory, I was using the aly.  Using the aly allowed me to add a filter on territory name matching.  Is it too late to revert back?  Adding a territory is a DB change, and a bunch of changes in the code. :)

**Comment by kheaactua** [comment]
I used the hyphens as they are classic Diplomacy, they can be dropped though.  As long as I can match territory names in the orders, I'm fine.  As many territories contain spaces and hyphens, the territory name should probably be enclosed in quotations or brackets.

i.e.
Red MOVE  "Gulf of Panama" "Pacific Mid-East"

**Comment by kheaactua** [comment]
Why did you change `%source%` to `%territory%`?

This wouldn't impose much of a change on my part (I'd just convert it to source when I get it), but doesn't this make the order format less clear?

**Comment by gobyrne** [comment]
- %Ally% doesn't quite work since it might not be unique. You could have 2 allied units adjacent but only 1 that you want to take over the space.
- Good point about the Quotations.
- I changed source to territory because we needed a third identification and I thought it was more descriptive then "mid". In this case %territory% is the current territory of the unit that the command is for. Destination is unchanged and %source% is now the initial square that the supported or convoyed unit is in.

**Comment by kheaactua** [comment]
Re: "%Ally% doesn't quite work since it might not be unique. You could have 2 allied units adjacent but only 1 that you want to take over the space."

Does that matter though?  I can't see it making a difference.  The way I use the support order is that on a contested territory, a support +1's it's ally's attack, regardless of where the ally attacks from.

**Comment by kheaactua** [comment]
Re "Good point about the Quotations." Feel free to use brackets if you prefer.  Up to you.

**Comment by kheaactua** [comment]
Re: Changing source to territory

I don't see anything wrong with this.  Will you need me to change the keys in the objects I return to you that use `source`/`dest`?  I was hoping to continue using though names, as refactoring those names might be a challenge. :)  Especially because in my code, `getSource()` returns a `State` object.  So renaming it would turn

``` php
$t = $order->getSource()->getTerritory();
```

to 

``` php
$t = $order->getTerritory()->getTerritory();
```

Plus the version of the ORM I'm using has a tendency to produce name collisions in function names based on column name.. and I'm sure this wouldn't help :)

**Comment by gobyrne** [comment]
Re: "%Ally% doesn't quite work since it might not be unique. You could have 2 allied units adjacent but only 1 that you want to take over the space."

It's possible that it could matter... for example you might only be helping that ally so that he moves his troop away from your base. Then he moves his other troop closer to your base and your unhappy.

It's not a big deal, so I don't really mind.

**Comment by gobyrne** [comment]
Re: Changing source to territory

Ok, so the names of the parameters don't matter to me at all. I actually don't even see the names, I just send you a bunch of numbers and an order.

**Comment by kheaactua** [comment]
Hmm, didn't think of that scenario.  Good catch.

**Comment by gobyrne** [comment]
Re "Good point about the Quotations." 

Wait a minute, I thought I'd be sending you the territory ID, not the name. Actually I've been sending IDs for everything.

**Comment by kheaactua** [comment]
That's good too.  This slutty app can take it all. :)

If you're sending IDs though, you might as well send a data structure rather than an order string.  No matter though.

**Comment by gobyrne** [comment]
That's good about the ID's. I'm going to close this issue since it's getting a bit broad. We can open more specific issues to resolve remaining concerns.

**Comment by kheaactua** [comment]
@gobyrne The orders are implemented as specified above, with the exception that territory names need to be wrapped in quotes.

The server accepts these.. well, it can interpret and validate them, I'm not sure about accepting yet.
