### ISSUE TITLE
App Directory Structure

### ISSUE THREAD

**Issue by kheaactua** [kheaactua/diplomacy-engine#5]
@gobyrne I noticed that the app directory is pretty flat.  I'd strongly recommend following a typical angular directory structure.  [Here is one suggestion](https://scotch.io/tutorials/angularjs-best-practices-directory-structure)

**Comment by gobyrne** [comment]
It's a good suggestion. Let's wait until I have more files than the number of directories that would need to be created to reorganize it. Thanks for the link!
